version: "3"
services:
 reverseproxy:
   image: turanmerter/reverseproxy
   ports:
     - 8080:8080
   restart: always
   depends_on:
    - backend-user
    - backend-feed   
 backend-user:
  image: turanmerter/udacity-restapi-user
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET 
   AWS_BUCKET: $AWS_MEDIA_BUCKET 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_REGION: $AWS_REGION 
   JWT_SECRET: $JWT_SECRET 
   POSTGRESS_DATABASE: $POSTGRESS_DATABASE 
   POSTGRESS_DB: $POSTGRESS_DATABASE 
   POSTGRESS_HOST: $POSTGRESS_HOST 
   POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
   POSTGRESS_USERNAME: $POSTGRESS_USERNAME
   URL: "http://localhost:8100"
 backend-feed:
  image: turanmerter/udacity-restapi-feed
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET 
   AWS_BUCKET: $AWS_MEDIA_BUCKET 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_REGION: $AWS_REGION 
   JWT_SECRET: $JWT_SECRET 
   POSTGRESS_DATABASE: $POSTGRESS_DATABASE 
   POSTGRESS_DB: $POSTGRESS_DATABASE 
   POSTGRESS_HOST: $POSTGRESS_HOST 
   POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
   POSTGRESS_USERNAME: $POSTGRESS_USERNAME
   URL: "http://localhost:8100"
 frontend:
  image: turanmerter/udacity-frontend
  ports:
   - "8100:80"