version: "3"
services:
 reverseproxy:
   build:
     context: udacity-c3-deployment/docker
   image: turanmerter/reverseproxy 
 backend_user:
   build:
     context: udacity-c3-restapi-user
   image: turanmerter/udacity-restapi-user
 backend_feed:
   build:
     context: udacity-c3-restapi-feed 
   image: turanmerter/udacity-restapi-feed
 frontend:
   build:
     context: udacity-c3-frontend 
   image: turanmerter/udacity-frontend